config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, path: 'users', path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up',
    registration: 'register',
  }, controllers: {
    sessions: 'users/sessions', as: 'users/sign-in',
    registrations: 'users/registrations',
  }

  authenticated :user do
    root to: 'events#index', as: :authenticated_root
    resources :events, only: [:new, :create, :index, :show] do
      collection do
        get :view_own, as: 'view-own'
      end
    end
    resources :tickets, only: [:new, :create, :index, :show]
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one :location, as: :locatable, dependent: :destroy
  has_many :tickets, dependent: :destroy

  validates :name, :date, :tickets_available, presence: true
  validates :tickets_available, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates_associated :location

  accepts_nested_attributes_for :location

  after_commit :clear_event_cache

  private

  def clear_event_cache
    Rails.cache.delete("events/index")
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :locatable, polymorphic: true

  validates :address, presence: true

  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }

  def full_coordinates
    "#{latitude}, #{longitude}"
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :user_id, :event_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy

  validates :email, :encrypted_password, :sign_in_count, :failed_attempts, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    authenticated_root_path
  end

  def current_ability
    @current_ability ||= ability_class.new(current_user)
  end

  private

  def ability_class
    "#{controller_name.classify}Ability".constantize
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    return @events.includes(:location).all unless Rails.application.config.cache_classes && Rails.env.development?
    @events = Rails.cache.fetch("events/index", expires_in: 12.hours) do
      Event.includes(:location).to_a
    end
  end

  def view_own
    @events = Event.where(user_id: current_user.id)
  end

  def new
    @event = Event.new
  end

  def show; end

  def create
    @event = current_user.events.build(create_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def create_params
    params.require(:event).permit(
      :name,
      :description,
      :date,
      :tickets_available,
      location_attributes: [
        :address
      ]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index; end

  def create
    TicketBookingJob.perform_later(create_params[:event_id], current_user.id, params[:ticket_count])
  rescue StandardError => e
    flash[:alert] = "Failed to book tickets: #{e.message}"
  end

  private

  def create_params
    params.permit(
      :event_id,
    )
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div class="error-messages mt-2">
    <ul class="alert-danger">
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: event, local: true) do |form| %>
  <div>
    <%= form.label :name, class: 'input-label' %>
    <%= form.text_field :name, class: 'input' %>
  </div>
  <div>
    <%= form.label :description, class: 'input-label' %>
    <%= form.text_field :description, class: 'input' %>
  </div>

  <div>
    <%= form.label :date, class: 'input-label' %>
    <%= form.datetime_field :date, as: :datetime, value: form.object.try(:strftime, "%m/%d/%Y"), class: 'input', min: Date.current %>
  </div>

  <div>
    <%= form.label :tickets_available, class: 'input-label' %>
    <%= form.number_field :tickets_available, value: form.object.present? ? form.object.tickets_available : 0, class: 'input', min: 0 %>
  </div>

  <%= form.fields_for :location, event.location.present? ? event.location : event.build_location do |fl| %>
    <%= fl.label :address, class: 'input-label' %>
    <%= fl.text_field :address, class: 'input' %>
  <% end %>


  <div class="mt-4 w-100 flex justify-items-end">
    <%= form.submit class: 'button-primary ml-auto' %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="p-8">
  <div class="w-100 flex justify-end">
    <%= link_to "New Event", new_event_path, class: 'button-primary mt-4' %>
  </div>

  <div class="grid grid-cols-4 mt-4 gap-4">
    <% @events.each do |event| %>
      <% cache event do %>
        <div class="card break-all">
          <p class="text-2xl font-medium pb-4"><%= event.name %></p>
          <p><%= event.description %></p>
          <p><%= event.date.in_time_zone(Time.zone).strftime('%B %d, %Y %I:%M %p') %></p>
          <p>Tickets remaining: <%= event.tickets_available %></p>
          <p>Location: <%= event.location.address %></p>
          <br/>
          <%= link_to "View", event_path(event), class: 'button-primary' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :content, flush: true do %>
  <div class="p-14 shadow-md rounded-2xl bg-slate-900 text-white w-[calc(100vw/3)]">
    <h2 class="text-3xl font-medium">New event</h2>
    <%= render 'form', event: @event %>
  </div>
<% end %>

<%= render 'shared/center_layout' %>

app/views/events/show.html.erb
<% cache @event do %>
  <div class="p-16">
    <div class="card break-all">
      <p class="text-2xl pb-4 font-medium"><%= @event.name %></p>
      <p><%= @event.description %></p>
      <p>Tickets remaining: <%= @event.tickets_available %></p>
      <p>Location: <%= @event.location.address %></p>

      <h1>Order</h1>
      <%= form_tag tickets_url do %>
        <%= hidden_field_tag :event_id, @event.id %>
        <div>
          <%= label_tag :ticket_count, "Amount", class: 'input-label' %>
          <%= number_field_tag :ticket_count, 1, class: 'input', min: 1 %>
        </div>

        <%= submit_tag 'Order', class: 'button-primary mt-4' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/view_own.html.erb
<div class="p-8">
  <div class="grid grid-cols-4 mt-4 gap-4">
    <% @events.each do |event| %>
      <% cache event do %>
        <div class="card break-all">
          <p class="text-2xl font-medium pb-4"><%= event.name %></p>
          <p><%= event.description %></p>
          <p><%= event.date.in_time_zone(Time.zone).strftime('%B %d, %Y %I:%M %p') %></p>
          <p>Tickets remaining: <%= event.tickets_available %></p>
          <p>Location: <%= event.location.address %></p>
          <br/>
          <%= link_to "View", event_path(event), class: 'button-primary' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% cache('landing_page') do %>
  <% content_for :content, flush: true do %>
    <h1>Jarred Baker</h1>
    <h1>Event booking</h1>
  <% end %>

  <%= render 'shared/center_layout' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JarredBakerEventBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-slate-800">
    <% if user_signed_in? %>
      <%= render 'shared/authed_nav' %>
    <% else %>
      <%= render 'shared/unauthed_nav' %>
    <% end %>
    <div class="absolute top-20 right-2">
      <% if notice.present? %>
        <p class="notice alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <div id="ticket-status" data-user-id="<%= user_signed_in? ? current_user.id : '' %>"></div>
      <div id="ticket-status-message"></div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_authed_nav.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to authenticated_root_path, class: 'flex items-center space-x-3 rtl:space-x-reverse' do %>
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Jarred Baker Event Booking</span>
    <% end %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li class="flex items-center">
          <%= link_to 'Orders', tickets_path, class: 'text-white' %>
        </li>
        <li class="flex items-center">
          <%= link_to 'My events', view_own_events_path, class: 'text-white' %>
        </li>
        <li>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'button-primary' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_center_layout.html.erb
<div class="flex w-screen h-screen">
  <div class="m-auto">
    <%= yield :content %>
  </div>
</div>

app/views/shared/_unauthed_nav.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to unauthenticated_root_path, class: 'flex items-center space-x-3 rtl:space-x-reverse' do %>
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Jarred Baker Event Booking</span>
    <% end %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'button-secondary' %>
          <%= link_to 'Login', new_user_session_path, class: 'button-primary' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tickets/index.html.erb
<div class="p-8">
  <div class="grid gap-4 grid-cols-4 mt-4 w-100">
    <% @tickets.includes(:event, event: :location).each do |ticket| %>
      <% cache ticket do %>
        <div class="card break-all">
          <p class="text-2xl pb-4 font-medium"><%= ticket.event.name %></p>
          <p><%= ticket.event.description %></p>
          <p><%= ticket.event.date.in_time_zone(Time.zone).strftime('%B %d, %Y %I:%M %p') %></p>
          <p>Location: <%= ticket.event.location.address %></p>

          <div class="mt-4 w-100 flex justify-items-end">
            <%= link_to "View Event", event_path(ticket.event), class: 'button-primary' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>